general {
    lock_cmd = pidof hyprlock || hyprlock       # Komento, jota kutsutaan lukituksessa
    before_sleep_cmd = loginctl lock-session    # Lukitse ennen nukkumaanmenoa
    after_sleep_cmd = niri msg action power-on-monitors # Herätä näytöt
}

# 1. Lukitse näyttö 10 minuutin toimettomuuden jälkeen
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 2. Sammuta näytöt 15 minuutin kohdalla
listener {
    timeout = 900
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
