color0 #212a30
color1 #fd4663
color2 #8ba9c1
color3 #7f82b3
color4 #967fb3
color5 #acc1d3
color6 #afb1d0
color7 #f2f2f3
color8 #616a71
color9 #fd4663
color10 #8ba9c1
color11 #7f82b3
color12 #967fb3
color13 #acc1d3
color14 #afb1d0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1f23
background            #1a1f23
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #212a30
active_border_color   #8ba9c1
inactive_border_color #212a30
url_color             #8ba9c1

active_tab_foreground   #1b1f22
active_tab_background   #8ba9c1
inactive_tab_foreground #afb3b6
inactive_tab_background #212a30
cursor_trail_color      #afb3b6
