font_family      JetBrains Mono
font_size        14.0
window_padding_width 0
background_opacity 0.95
confirm_os_window_close 0
enable_audio_bell no

linux_display_server wayland
hide_window_decorations yes
include themes/noctalia.conf

clear_all_shortcuts yes

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
